# Generated by Django 4.2.3 on 2023-07-27 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['date_from']},
        ),
        migrations.AlterField(
            model_name='client',
            name='pesel',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clienttrip',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='api.client'),
        ),
        migrations.AlterField(
            model_name='clienttrip',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='api.trip'),
        ),
        migrations.AlterField(
            model_name='countrytrip',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='api.country'),
        ),
        migrations.AlterField(
            model_name='countrytrip',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='api.trip'),
        ),
    ]
