# Generated by Django 4.2.3 on 2023-07-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_trip_options_alter_client_pesel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttrip',
            name='payment_date',
            field=models.DateTimeField(null=True),
        ),
    ]
