# Generated by Django 4.2.3 on 2023-07-27 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_clienttrip_payment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
