# Generated by Django 4.2.3 on 2023-07-27 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_first_name_client_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttrip',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='api.client'),
        ),
    ]
