# Generated by Django 4.2.3 on 2023-07-27 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.PositiveIntegerField()),
                ('details', models.CharField(max_length=255)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.medicament')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.prescription')),
            ],
        ),
    ]
