# Generated by Django 4.2.3 on 2023-07-27 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_rename_firstname_doctor_firs_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
