# Generated by Django 4.2.3 on 2023-07-27 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_rename_firs_name_doctor_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionmedicament',
            name='medicament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='hospital.medicament'),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicament',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='hospital.prescription'),
        ),
    ]
