# Generated by Django 4.2.3 on 2023-07-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='fulfilled_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='productwarehouse',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
