# Generated by Django 4.2.3 on 2023-07-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_alter_order_created_at_alter_order_fulfilled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fulfilled_at',
            field=models.DateTimeField(null=True),
        ),
    ]
